bodegaDeltec/applications/resources/urls.py
from django.urls import path

from . import views
from applications.resources.views import quitar_asignacion_recurso

app_name = "resources_app"

urlpatterns = [
    path(
        'registrar-recurso/', 
        views.ResourceRegisterView.as_view(),
        name='registrar-recurso',
    ),
    path(
        'administrar-recursos/', 
        views.ResourcesListView.as_view(),
        name='administrar-recursos',
    ),
    path(
        'detalle-asignacion-recurso/<pk>', 
        views.DetalleAsignacionRecursoView.as_view(),
        name='detalle-asignacion-recurso',
    ),
    path(
        'quitar-asignacion-recurso/<pk>', 
        quitar_asignacion_recurso,
        name='quitar-asignacion-recurso',
    ),
    path(
        'asignar-recurso/<pk>', 
        views.AsignarRecursoView.as_view(),
        name='asignar-recurso',
    ),

]

bodegaDeltec/bodegaDeltec/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.resources.urls')),
]

bodegaDeltec/templates/resources/administrar-recursos.html
{% extends 'base_generic.html' %}


{% block title %}Administrar Usuarios{% endblock title %}


{% block header %}
    {% include 'includes/navbar.html' %}                        
{% endblock header %}

{% block content %}

<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <form class="d-flex" method="GET">
        <input class="form-control me-2" id="kword" name="kword" type="search" placeholder="Buscar Codigo Recurso" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
      <a class="btn btn-outline-success" href="{% url 'resources_app:registrar-recurso' %}" role="button">Nuevo Registro</a>
    </div>
</nav>

<table class="table">
    <thead class="table-secondary">
        <tr>
            <th scope="col">Categoria</th>
            <th scope="col">Codigo</th>
            <th scope="col">Nombre</th>
            <th scope="col" style="text-align:Left;">Opciones</th>
          </tr>
    </thead>
    <tbody>
                
        {% for recurso in  recursos %}
        <tr>
            <td scope="row">{{ recurso.categoria        }}</th>
            <td scope="row">{{ recurso.codigo           }}</th>
            <td scope="row">{{ recurso.nombre           }}</td>             
            {% if recurso.id_user_asignado %}
            <td scope="row" style="text-align:left;">
              <a class="btn btn-outline-success" href="{% url 'resources_app:detalle-asignacion-recurso' pk=recurso.id %}">Ver Detalle Asignacion</a>
            </td> 
            {% else %}
            <td scope="row" style="text-align:left;">
              <a class="btn btn-outline-success" href="{% url 'resources_app:asignar-recurso' pk=recurso.id%}" role="button">Asignar</a>              
            </td>              
            {% endif %}                    

        </tr>
        {% endfor %}                    
 
    </tbody>
  </table>

{% endblock content %}
    
    

bodegaDeltec/templates/resources/asignar-recurso.html
{% extends 'base_generic.html' %}


{% block title %}Asignar Recurso{% endblock title %}


{% block header %}
    {% include 'includes/navbar.html' %}                        
{% endblock header %}

{% block content %}

<form class="row g-3" method="post">
  {% csrf_token %}
  <div class="card text-center">
    <div class="card-header">
      Asignar Recurso Codigo : {{objeto.codigo}}
    </div>
    <div class="card-body">    
      <h5 class="card-text">{{objeto.nombre}}</h5>
      <p class="card-text">{{objeto.descripcion}}</p>
    </div>

    {{form.id_user_asignado}}  
    
      
  </div>
  <div class="d-grid gap-2">
      <button type="submit" class="btn btn-primary">Guardar Cambios</button>
  </div>
</form>

{% endblock content %}
    
    

bodegaDeltec/templates/resources/detalle-asignacion.html
{% extends 'base_generic.html' %}


{% block title %}Detalle Asignacion{% endblock title %}


{% block header %}
    {% include 'includes/navbar.html' %}                        
{% endblock header %}

{% block content %}

<div class="card text-center">
  <div class="card-header">
    Detalle Asignacion
  </div>
  <div class="card-body">
    <h5 class="card-title">{{objeto.nombre}}</h5>
    <p class="card-text">{{objeto.descripcion}}</p>
    <p class="card-text">Asignado a : {{objeto.id_user_asignado}}</p>    
  
 </div>
 <div class="card-footer">
    <a href="{% url 'resources_app:administrar-recursos' %}" class="btn btn-primary">Volver</a>
    <a href="{% url 'resources_app:quitar-asignacion-recurso' pk=objeto.id %}" class="btn btn-primary">Quitar Asignacion</a>
  </div>

</div>

{% endblock content %}
    
    

bodegaDeltec/templates/resources/register.html
{% extends 'base_generic.html' %}


{% block title %}User Register{% endblock title %}



{% block header %}
    {% include 'includes/navbar.html' %}                        
{% endblock header %}
    

{% block content %}

<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <div class="row">
            <div class="col-lg-5 d-none d-lg-block"></div>
            <div class="col-lg-7">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Registrar Recursos</h1>
                    </div>
                    <form class="row g-3" method="post">
                        {% csrf_token %}
                        
                        {{form.categoria}}
                        {{form.codigo}}
                        {{form.nombre}}
                        {{form.descripcion}}
                        
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Registrar</button>
                        </div>
                      </form>
                    <hr>                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
    
    