bodegaDeltec/applications/home/urls.py
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [
    path(
        'home/', 
        views.HomePageView.as_view(),
        name='home-page',
    ),
]

bodegaDeltec/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.UserLoginView.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.UserLogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'administrar-usuarios/', 
        views.UserListView.as_view(),
        name='administrar-usuarios',
    ),
    path(
        'ver-recursos-asignados/<id_user>', 
        views.UserAsignacionesListView.as_view(),
        name='ver-recursos-asignados',
    ),
]

bodegaDeltec/bodegaDeltec/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.resources.urls')),
]

bodegaDeltec/templates/includes/navbar.html
<nav class="navbar navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home_app:home-page' %}">Home</a>
    <a class="navbar-brand">Administrador : {{user.get_full_name}}</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Opciones de Aministrador</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home_app:home-page' %}">Home</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'users_app:user-logout' %}">Cerrar Sesion</a>
          </li>
            
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

<br><br><br><br>