bodegaDeltec/applications/resources/urls.py
from django.urls import path

from . import views
from applications.resources.views import quitar_asignacion_recurso

app_name = "resources_app"

urlpatterns = [
    path(
        'registrar-recurso/', 
        views.ResourceRegisterView.as_view(),
        name='registrar-recurso',
    ),
    path(
        'administrar-recursos/', 
        views.ResourcesListView.as_view(),
        name='administrar-recursos',
    ),
    path(
        'detalle-asignacion-recurso/<pk>', 
        views.DetalleAsignacionRecursoView.as_view(),
        name='detalle-asignacion-recurso',
    ),
    path(
        'quitar-asignacion-recurso/<pk>', 
        quitar_asignacion_recurso,
        name='quitar-asignacion-recurso',
    ),
    path(
        'asignar-recurso/<pk>', 
        views.AsignarRecursoView.as_view(),
        name='asignar-recurso',
    ),

]

bodegaDeltec/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.UserLoginView.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.UserLogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'administrar-usuarios/', 
        views.UserListView.as_view(),
        name='administrar-usuarios',
    ),
    path(
        'ver-recursos-asignados/<id_user>', 
        views.UserAsignacionesListView.as_view(),
        name='ver-recursos-asignados',
    ),
]

bodegaDeltec/bodegaDeltec/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.resources.urls')),
]

bodegaDeltec/applications/users/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

#

from .functions import validate_id_user, validate_name, validate_last_name
from .managers  import UserManager

class User(AbstractBaseUser, PermissionsMixin):
    id_user     = models.CharField(max_length=20,unique=True,validators=[validate_id_user])
    name        = models.CharField(max_length=50,validators=[validate_name])
    last_name   = models.CharField(max_length=50,validators=[validate_last_name])
    is_staff    = models.BooleanField(default=False)

    USERNAME_FIELD  = 'id_user'
    REQUIRED_FIELDS = ['name', 'last_name']

    objects = UserManager()

    def get_username(self):
        return self.name

    def get_full_name(self):
        return self.name + ' ' + self.last_name

bodegaDeltec/applications/users/forms.py
from django import forms
from .models import User
from django.contrib.auth import authenticate

class UserRegisterForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'id_user',
            'name',
            'last_name')

        widgets = {
            'id_user':forms.TextInput(
                attrs={
                    'type':'text',
                    'class':'form-control',
                    'placeholder':'Numero Identificacion',
                    'name':'id_user',
                    'arial-label':'Numero Identificacion'

                }
            ),
            'name':forms.TextInput(
                attrs={
                    'type':'text',
                    'class':'form-control',
                    'placeholder':'Nombres',
                    'name':'name',
                    'arial-label':'Nombres'

                }
            ),
            'last_name':forms.TextInput(
                attrs={
                    'type':'text',
                    'class':'form-control',
                    'placeholder':'Apellidos',
                    'name':'last_name',
                    'arial-label':'Apellidos'

                }
            ),            
        }

    def clean_id_user(self):
        id_user = self.cleaned_data['id_user']
        id_user_exist = User.objects.filter(id_user=id_user).exists()
        if id_user_exist:
            raise forms.ValidationError('El numero de identificacion ya existe')
        return id_user


class UserLoginForm(forms.Form):
    
    id_user=forms.CharField(
        label='Numero Identificacion',
        required=True,
        widget=forms.TextInput(
            attrs={
                'type':'text',
                'class':'form-control',
                'placeholder':'Numero Identificacion',
                'name':'id_user',
                'arial-label':'Numero Identificacion'
            }
        )
    )

    
    password=forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'type':'password',
                'class':'form-control',
                'placeholder':'Contraseña',
                'name':'password'
                
            }
        )
    )

    def clean(self):
        id_user = self.cleaned_data['id_user']
        password = self.cleaned_data['password']        
        id_user_exist = User.objects.filter(id_user=id_user).exists()
        if not id_user_exist:
            self.add_error('id_user','El numero de identificacion no se encuentra registrado')
        else:
            if id_user and password:
                user = authenticate(
                    id_user  = id_user,
                    password = password       
                )
                if not user:
                    self.add_error('password','La contraseña es incorrecta')
        return super(UserLoginForm,self).clean() 

bodegaDeltec/applications/users/views.py
# Create your views here.
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import View, ListView
from django.views.generic.edit import FormView


from .forms import UserRegisterForm, UserLoginForm

from .models import User

from applications.resources.models import Resource


class UserRegisterView(LoginRequiredMixin,FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('home_app:home-page')
    login_url = reverse_lazy('users_app:user-login')


    def form_valid(self, form):
        
        User.objects.create_user(
            form.cleaned_data['id_user'],
            form.cleaned_data['name'],
            form.cleaned_data['last_name']
        )

        return super(UserRegisterView, self).form_valid(form)


class UserLoginView(FormView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    success_url = reverse_lazy('home_app:home-page')


    def form_valid(self, form):
        user = authenticate(
            id_user  = form.cleaned_data['id_user'],
            password = form.cleaned_data['password']
        )

        login(self.request, user)
    
        return super(UserLoginView, self).form_valid(form)


class UserLogoutView(LoginRequiredMixin,View):
    login_url = reverse_lazy('users_app:user-login')

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )


class UserListView(ListView):
    model = User
    template_name = "users/administrar-usuarios.html"
    context_object_name = 'usuarios'

    def get_queryset(self):

        palabra_clave = self.request.GET.get("kword",'')

        lista_usuarios = User.objects.filtrar_usuarios(palabra_clave)
        
        return lista_usuarios

class UserAsignacionesListView(ListView):
    model = User
    template_name = "users/ver-recursos-asignados.html"
    context_object_name = 'recursos'

    def get_queryset(self):
        
        id_user = self.kwargs['id_user']
        datos_detalle = Resource.objects.consultar_recursos_asignados(id_user)
        return datos_detalle

     

bodegaDeltec/templates/users/administrar-usuarios.html
{% extends 'base_generic.html' %}


{% block title %}Administrar Usuarios{% endblock title %}


{% block header %}
    {% include 'includes/navbar.html' %}                        
{% endblock header %}

{% block content %}

<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <form class="d-flex" method="GET">
        <input class="form-control me-2" id="kword" name="kword" type="search" placeholder="Buscar empleado" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
      <a class="btn btn-outline-success" href="{% url 'users_app:user-register' %}" role="button">Nuevo Registro</a>
    </div>
  </nav>

<table class="table">
    <thead class="table-secondary">
        <tr>
            <th scope="col">Numero Identificacion</th>
            <th scope="col">Nombres</th>
            <th scope="col">Apellidos</th>
            <th scope="col" style="text-align:center;">Opciones</th>
          </tr>
    </thead>
    <tbody>
                
        {% for usuario in  usuarios %}
        <tr>
            <th scope="row">{{ usuario.id_user      }}</th>
            <td scope="row">{{ usuario.name         }}</td>
            <td scope="row">{{ usuario.last_name    }}</td>
            <td scope="row" style="text-align:center;">
                <a class="btn btn-outline-success" href="{% url 'users_app:ver-recursos-asignados' id_user=usuario.id %}" role="button">Ver recursos asignados</a>
            </td>
        </tr>
        {% endfor %}                    
 
    </tbody>
  </table>



{% endblock content %}
    
    

bodegaDeltec/templates/users/login.html
{% extends 'base_generic.html' %}


{% block title %}Login{% endblock title %}


{% block content %}

<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <div class="row">
            <div class="col-lg-5 d-none d-lg-block"></div>
            <div class="col-lg-7">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Ingresar al sistema</h1>
                    </div>
                    <form class="row g-3" method="post">
                        {% csrf_token %}
                         
                        <div class="row g-3">                          
                            <div class="col-12">                                
                                {{form.id_user}}
                                {% if form.id_user.errors %}
                                    <div class="alert-danger">
                                         <strong>{{ form.id_user.errors }}</strong>
                                    </div>
                                {% endif %}
                                                       
                            </div>

                            <div class="col-12">
                                {{form.password}}
                                {% if form.password.errors %}
                                    <div class="alert-danger">
                                         <strong>{{ form.password.errors }}</strong>
                                    </div>
                                {% endif %}

                            </div>

                        </div>

                        <div class="d-grid gap-2">
                          <button type="submit" class="btn btn-primary">Ingresar</button>
                        </div>
                      </form>
                    <hr>                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
    
    

bodegaDeltec/templates/users/register.html
{% extends 'base_generic.html' %}


{% block title %}User Register{% endblock title %}



{% block header %}
    {% include 'includes/navbar.html' %}                        
{% endblock header %}
    

{% block content %}

<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <div class="row">
            <div class="col-lg-5 d-none d-lg-block"></div>
            <div class="col-lg-7">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Registrar colaboradores</h1>
                    </div>
                    <form class="row g-3" method="post">
                        {% csrf_token %}
                         
                        <div class="row g-3">                          
                            <div class="col-12">                                
                                {{form.id_user}}

                                {% if form.id_user.errors %}
                                <div class="alert-danger" role="alert">
                                    <strong>{{ form.id_user.errors|escape }}</strong>                                
                                </div>    
                                {% endif %}
                                                       
                            </div>

                            <div class="col-12">
                                {{form.name}}

                                {% if form.name.errors %}
                                <div class="alert-danger" role="alert">
                                    <strong>{{ form.name.errors|escape }}</strong>                                
                                </div>
                                {% endif %}

                            </div>

                            <div class="col-12">
                                {{form.last_name}}

                                {% if form.last_name.errors %}
                                <div class="alert-danger" role="alert">
                                    <strong>{{ form.last_name.errors|escape }}</strong>                                
                                </div>
                                {% endif %}
                            </div>

                        </div>

                        <div class="d-grid gap-2">
                          <button type="submit" class="btn btn-primary">Registrar</button>
                        </div>
                      </form>
                    <hr>                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
    
    

bodegaDeltec/templates/users/ver-recursos-asignados.html
{% extends 'base_generic.html' %}


{% block title %}Administrar Usuarios{% endblock title %}


{% block header %}
    {% include 'includes/navbar.html' %}                        
{% endblock header %}

{% block content %}


<div class="card text-center">
    <div class="card-header">
      Detalle Asignacion
    </div>
    <div class="card-body">

      <table class="table">
        <thead class="table-secondary">
            <tr>
                <th scope="col">Categoria</th>
                <th scope="col">Codigo</th>
                <th scope="col">Nombre</th>
                <th scope="col" style="text-align:center;">Opciones</th>
              </tr>
        </thead>
        <tbody>
                    
            {% for recurso in  recursos %}
            <tr>
                <th scope="row">{{ recurso.categoria      }}</th>
                <td scope="row">{{ recurso.codigo         }}</td>
                <td scope="row">{{ recurso.nombre    }}</td>
                <td scope="row" style="text-align:center;">
                    <a class="btn btn-outline-success" href="{% url 'resources_app:detalle-asignacion-recurso' pk=recurso.id %}" role="button">Ver Detalle Asignacion</a>
                </td>
            </tr>
            {% endfor %}                    
     
        </tbody>
      </table>

   </div>
   <div class="card-footer">
      <a href="{% url 'users_app:administrar-usuarios' %}" class="btn btn-primary">Volver</a>
    </div>
  
</div>



{% endblock content %}
    
    